import pandas as pd
import requests 

def download_images(image_links, folder_name, current):
    for link in image_links: # iterate through all the image links
        file_name = f'C:/Users/chibi/OneDrive/GitHub/SDP_2022-2023/Dataset/{folder_name}/{current}.jpg' # generate image file name
        r = requests.get(link).content

        with open(file_name, 'wb') as f:
            f.write(r) # save the image
        
        current += 1 # update the image number for the next iteration
    return current

if __name__ == '__main__':
    # open the excel sheet generated by iNaturalist (contains links to images)
    df = pd.read_excel('C:/Users/chibi/OneDrive/GitHub/SDP_2022-2023/temp.xlsx') 

    # convert the image url column into a list
    image_links = df["image_url"].tolist()

    # specify the folder name
    folder_name = "Poison_Sumac"

    # naming convention of the images are by #
    current = 3582

    # download the images given the urls
    download_images(image_links, folder_name, current)

    print("Done!")